### ISSUE TITLE
Terraform fails to create a schema because of the order of permissions

### ISSUE THREAD

**Issue by verbotenj** [getindata/terraform-snowflake-schema#13]
Apply schema

Error: 003511 (23001): SQL compilation error: Privilege order violation for the future grants on stage. READ should be granted before/simultaneously with WRITE.

Workaround: It works in 2nd run

**Comment by dgniewek** [comment]
Hi @verbotenj - thanks for getting in touch.

We're aware of that problem and your WA :smiley: .

This issue will be resolved after code-refactor using `snowflake_grant_privileges_to_role` terraform resource that we're planning in the near future.

**Comment by moss2k13** [comment]
@verbotenj version [v2.0.0+](https://github.com/getindata/terraform-snowflake-schema/releases/tag/v2.0.0) should fix your problem.
